foreground #dfe3e7
background #0f1417
cursor #8bd0ef
cursor_text_color #c0c8cd
selection_foreground #1f333c
selection_background #b4cad6
url_color #8bd0ef

color0 #0f1417
color1 #ffb4ab
color2 #c6c2ea
color3 #b4cad6
color4 #8bd0ef
color5 #c6c2ea
color6 #b4cad6
color7 #dfe3e7

color8 #c0c8cd
color9 #ffb4ab
color10 #c6c2ea
color11 #b4cad6
color12 #8bd0ef
color13 #c6c2ea
color14 #b4cad6
color15 #dfe3e7
