source = ~/.config/hypr/colors.conf

background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size    = 5
    brightness   = 0.6
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = $on_surface
    font_size   = 72
    font_family = JetBrainsMono Nerd Font Bold
    position    = 0, 100
    halign      = center
    valign      = center
}

label {
    monitor =
    text = cmd[update:60000] echo "$(date +"%A, %d %B")"
    color = $on_surface_variant
    font_size   = 16
    font_family = JetBrainsMono Nerd Font
    position    = 0, 28
    halign      = center
    valign      = center
}

input-field {
    monitor =
    size             = 280, 52
    outline_thickness = 2
    dots_size        = 0.28
    dots_spacing     = 0.25
    outer_color      = $primary
    inner_color      = $surface_container
    font_color       = $on_surface
    fade_on_empty    = true
    placeholder_text = <i>Enter password...</i>
    hide_input       = false
    rounding         = 12
    check_color      = $primary
    fail_color       = $error
    fail_text        = <i>Wrong password ($ATTEMPTS)</i>
    position         = 0, -60
    halign           = center
    valign           = center
}
